language: python
python:
    - "2.6"
    - "2.7"
env:
    - DJANGO=1.4
    - DJANGO=1.4.1
    - DJANGO=1.4.2
    - DJANGO=1.4.3
    - DJANGO=1.4.5
    - DJANGO=1.5
    - DJANGO=1.5.1
install:
    - pip install -r requirements.txt --use-mirrors
    - pip install -q Django==$DJANGO --use-mirrors
    - sudo apt-get update -qq
    - sudo apt-get install -qq tesseract-ocr
script: build.sh
notifications:
    email:
        on_failure: change
