language: python
python:
    - "2.6"
    - "2.7"
    - "3.2"
    - "3.3"
env:
    - DJANGO=1.1.3
    - DJANGO=1.1.4
    - DJANGO=1.2
    - DJANGO=1.2.1
    - DJANGO=1.2.2
    - DJANGO=1.2.3
    - DJANGO=1.2.4
    - DJANGO=1.2.5
    - DJANGO=1.2.6
    - DJANGO=1.2.7
    - DJANGO=1.3
    - DJANGO=1.3.1
    - DJANGO=1.3.2
    - DJANGO=1.3.3
    - DJANGO=1.3.4
    - DJANGO=1.3.5
    - DJANGO=1.3.6
    - DJANGO=1.3.7
    - DJANGO=1.4
    - DJANGO=1.4.1
    - DJANGO=1.4.2
    - DJANGO=1.4.3
    - DJANGO=1.4.4
    - DJANGO=1.4.5
    - DJANGO=1.5
    - DJANGO=1.5.1
install:
    - pip install -r requirements.txt --use-mirrors
    - pip install -q Django==$DJANGO --use-mirrors
script: python manage.py test
notifications:
    email:
        on_failure: change
