BEGIN TRANSACTION;

INSERT INTO "model_station" VALUES(1,'2','Glienicke/Nordbahn');
INSERT INTO "model_station" VALUES(2,'1','Birkenwerder');
INSERT INTO "model_station" VALUES(3,'3','Hennigsdorf');
INSERT INTO "model_station" VALUES(4,'4','Hohen Neuendorf');
INSERT INTO "model_station" VALUES(5,'6','Oranienburg');
INSERT INTO "model_station" VALUES(6,'7','Velten');
INSERT INTO "model_station" VALUES(7,'8','Fürstenberg/Havel');
INSERT INTO "model_station" VALUES(8,'9','Gransee');
INSERT INTO "model_station" VALUES(9,'10','Kremmen');
INSERT INTO "model_station" VALUES(10,'11','Liebenwalde');
INSERT INTO "model_station" VALUES(11,'12','Löwenberger Land');
INSERT INTO "model_station" VALUES(12,'13','Oberkrämer');
INSERT INTO "model_station" VALUES(13,'15','Mühlenbecker Land');
INSERT INTO "model_station" VALUES(14,'16','Zehdenick');

INSERT INTO "model_enginetype" VALUES(1,'32','Drehleiter (18/12)');
INSERT INTO "model_enginetype" VALUES(2,'10','Führungskraftwagen (FüKW)');
INSERT INTO "model_enginetype" VALUES(3,'11','Einsatzleitwagen (ELW 1)');
INSERT INTO "model_enginetype" VALUES(4,'12','Einsatzleitwagen (ELW 2)');
INSERT INTO "model_enginetype" VALUES(5,'13','Kommandofahrzeug (ELF-K)');
INSERT INTO "model_enginetype" VALUES(6,'15','Luftbeobachter (LuB)');
INSERT INTO "model_enginetype" VALUES(7,'19','Mannschaftstransportwagen');
INSERT INTO "model_enginetype" VALUES(8,'20','TLF16 W50 , S4000');
INSERT INTO "model_enginetype" VALUES(9,'21','LF8/18 , TLF16/24');
INSERT INTO "model_enginetype" VALUES(10,'23','TLF16/25');
INSERT INTO "model_enginetype" VALUES(11,'24','LF24/50 , TLF24/48 , TLF16/46');
INSERT INTO "model_enginetype" VALUES(12,'25','LF32 (Tatra)');
INSERT INTO "model_enginetype" VALUES(13,'27','Trockentanklöschfahrzeug (TroTLF16)');
INSERT INTO "model_enginetype" VALUES(14,'28','Trockenlöschfahrzeug TroLF');
INSERT INTO "model_enginetype" VALUES(15,'29','Sonstige Löschfahrzeuge (LF)');
INSERT INTO "model_enginetype" VALUES(16,'30','Drehleiter (DL30 W50)');
INSERT INTO "model_enginetype" VALUES(17,'31','Drehleiter (DL18 , DL(K)16/4 , DL(K)12/9)');
INSERT INTO "model_enginetype" VALUES(18,'33','Drehleiter (DL30 , DL(K)23/12)');
INSERT INTO "model_enginetype" VALUES(19,'35','Gelenkmast (GK)');
INSERT INTO "model_enginetype" VALUES(20,'36','Teleskopmast (TM)');
INSERT INTO "model_enginetype" VALUES(21,'39','Sonstige Hubrettungsfahrzeuge');
INSERT INTO "model_enginetype" VALUES(22,'40','Kleinlöschfahrzeug (KLF B100)');
INSERT INTO "model_enginetype" VALUES(23,'41','Löschfahrzeug (LF8)');
INSERT INTO "model_enginetype" VALUES(24,'42','Löschfahrzeug (LF8/6 , LF10/6)');
INSERT INTO "model_enginetype" VALUES(25,'44','Löschfahrzeug (F16 , LF16/12 , LF20/16)');
INSERT INTO "model_enginetype" VALUES(26,'45','Löschfahrzeug (LF16-TS)');
INSERT INTO "model_enginetype" VALUES(27,'46','Löschfahrzeug (LF24)');
INSERT INTO "model_enginetype" VALUES(28,'47','Tragkraftspritzenfahrzeug (TSF)');
INSERT INTO "model_enginetype" VALUES(29,'48','Tragkraftspritzenfahrzeug (TSF-W)');
INSERT INTO "model_enginetype" VALUES(30,'49','Vorausfahrzeug (VFZ)');
INSERT INTO "model_enginetype" VALUES(31,'50','Voraus-Rüstwagen (VRW)');
INSERT INTO "model_enginetype" VALUES(32,'51','Rüstwagen (RW1)');
INSERT INTO "model_enginetype" VALUES(33,'52','Rüstwagen (RW2)');
INSERT INTO "model_enginetype" VALUES(34,'53','Rüstwagen (RW3)');
INSERT INTO "model_enginetype" VALUES(35,'54','Gerätewagen Gefahrgut (GW-G , GW-G1)');
INSERT INTO "model_enginetype" VALUES(36,'55','Gerätewagen Öl (GW-Öl , GW-G2)');
INSERT INTO "model_enginetype" VALUES(37,'56','Gerätewagen Atemschutz (GW-A)');
INSERT INTO "model_enginetype" VALUES(38,'57','Gerätewagen Messtechnik / Strahlenschutz (GW-Mess, GW-S)');
INSERT INTO "model_enginetype" VALUES(39,'58','Gerätewagen Wasserrettung (GW-W)');
INSERT INTO "model_enginetype" VALUES(40,'59','Sonstige Gerätewagen (GW)');
INSERT INTO "model_enginetype" VALUES(41,'60','Schlauchwagen (SW12, SW14)');
INSERT INTO "model_enginetype" VALUES(42,'61','Schlauchwagen (SW1000)');
INSERT INTO "model_enginetype" VALUES(43,'62','Schlauchwagen (SW2000)');
INSERT INTO "model_enginetype" VALUES(44,'63','Schlauchwagen (SW2000-Tr)');
INSERT INTO "model_enginetype" VALUES(45,'64','Schlauchtransportwagen (STW)');
INSERT INTO "model_enginetype" VALUES(46,'65','Wechselladerfahrzeug (WLF)');
INSERT INTO "model_enginetype" VALUES(47,'66','sonstige Schlauch- und Wechselbehälterfahrzeuge');
INSERT INTO "model_enginetype" VALUES(48,'71','Feuerwehrkran (FWK)');
INSERT INTO "model_enginetype" VALUES(49,'72','Kleineinsatzfahrzeug (KEF)');
INSERT INTO "model_enginetype" VALUES(50,'73','Gerätewagen (RTGW)');
INSERT INTO "model_enginetype" VALUES(51,'74','Lastkraftwagen (LKW)');
INSERT INTO "model_enginetype" VALUES(52,'75','Gerätewagen Licht (GW-Li)');
INSERT INTO "model_enginetype" VALUES(53,'76','Kraftrad (KRAD)');
INSERT INTO "model_enginetype" VALUES(54,'77','Tankwagen / Tankfahrzeug (TW)');
INSERT INTO "model_enginetype" VALUES(55,'78','Löschboot (LB)');
INSERT INTO "model_enginetype" VALUES(56,'79','Mehrzweckboot (MZB)');
INSERT INTO "model_enginetype" VALUES(57,'81','Notarztwagen (NAW)');
INSERT INTO "model_enginetype" VALUES(58,'82','Notarzteinsatzfahrzeug (NEF)');
INSERT INTO "model_enginetype" VALUES(59,'83','Rettubgswagen (RTW)');
INSERT INTO "model_enginetype" VALUES(60,'84','Rettungshubschrauber (RTH)');
INSERT INTO "model_enginetype" VALUES(61,'85','Krankentransportwagen (KTW)');
INSERT INTO "model_enginetype" VALUES(62,'86','Hilfskrankentransportwagen (HKTW)');
INSERT INTO "model_enginetype" VALUES(63,'87','Großraum-Krankentransportwagen');
INSERT INTO "model_enginetype" VALUES(64,'88','Rettungsboot (RTB)');
INSERT INTO "model_enginetype" VALUES(65,'89','Sonstige Rettungsfahrzeuge');
INSERT INTO "model_enginetype" VALUES(66,'01','Kreisbrandmeister (KBM)');
INSERT INTO "model_enginetype" VALUES(67,'02','1. Vertreter (KBM)');
INSERT INTO "model_enginetype" VALUES(68,'03','2. Vertreter (KBM)');

INSERT INTO "model_engine" VALUES(1,1,1,'1');
INSERT INTO "model_engine" VALUES(2,1,3,'1');
INSERT INTO "model_engine" VALUES(3,1,7,'1');
INSERT INTO "model_engine" VALUES(4,1,10,'1');
INSERT INTO "model_engine" VALUES(5,1,25,'1');
INSERT INTO "model_engine" VALUES(6,6,18,'1');
INSERT INTO "model_engine" VALUES(7,2,25,'1');

COMMIT;
